version: "3.8"

services:
  ganhatempo:
    image: galantadev/ganhatempo:cd55bee26c66294f19bfb020254e42c58818c6e3
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - ganhatempo_net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=ganhatempo_net"
      - "traefik.http.routers.ganhatempo.rule=Host(`ganhatempo.galanta.com.br`)"
      - "traefik.http.routers.ganhatempo.entrypoints=websecure"
      - "traefik.http.routers.ganhatempo.tls.certresolver=myresolver"
      - "traefik.http.services.ganhatempo.loadbalancer.server.port=80"

networks:
  ganhatempo_net:
    external: true
