version: "3.8"

services:
  ganhatempo-bot:
    build:
      context: .
    restart: always
    ports:
      - "5173:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ganhatempo.rule=Host(`ganhatempo.galanta.com.br`)"
      - "traefik.http.routers.ganhatempo.entrypoints=websecure"
      - "traefik.http.routers.ganhatempo.tls.certresolver=myresolver"
      - "traefik.http.services.ganhatempo.loadbalancer.server.port=80"
    networks:
      - web

networks:
  web:
    name: web
    external: true
